//
// Created by presmanes3 on 10/1/20.
//

#ifndef TIMERMANAGERPROJECT_TIMERMANAGERCONSTANTS_H
#define TIMERMANAGERPROJECT_TIMERMANAGERCONSTANTS_H


/**** TIMER ****/

#define TIMER_FLAG_ACTIVATED true
#define TIMER_FLAG_DEACTIVATED false

#define TIMER_STATUS_ON true
#define TIMER_STATUS_OFF false


/**** TIMER MANAGER ****/

#define TIMER_MANAGER_DEFAULT_MAX_TIMERS 5

#define TIMER_MANAGER_IDENTIFIER_MAX_LENGTH 25
#define TIMER_MANAGER_DEFAULT_IDENTIFIER "DEFAULT"

#define TIMER_MANAGER_ACTIVATED true
#define TIMER_MANAGER_DEACTIVATED false

#endif //TIMERMANAGERPROJECT_TIMERMANAGERCONSTANTS_H
